/* M03 instructor helper. Do not edit this file for the homework solution. */
(() => {
    "use strict";

    const VERSION = "2026.06.13-m03.1";
    const EXPECTED_UTILS_HASH = "sha256:8f9f47e385b30f1c172c7f455b98fc93b982d0ee7fa932241f818d849e931384";
    const HASH_LINE = 'const EXPECTED_UTILS_HASH = "__M03_UTILS_HASH__";';
    const loadedScript = document.currentScript;

    function setupPage() {
        const content = document.querySelector(".content");
        if (content && content.dataset.m03Expanded !== "true") {
            const p = content.querySelector("p");
            if (p) {
                for (let i = 0; i < 20; i++) {
                    content.appendChild(p.cloneNode(true));
                }
                content.dataset.m03Expanded = "true";
            }
        }

        const header = document.querySelector("header");
        if (header && header.dataset.m03Timestamped !== "true") {
            header.textContent += " " + new Date().toLocaleString("en-US");
            header.dataset.m03Timestamped = "true";
        }
    }

    function normalizeSourceForHash(source) {
        const normalized = source
            .replace(/\r\n?/g, "\n")
            .replace(/const EXPECTED_UTILS_HASH = "(?:sha256:[a-f0-9]{64}|__PENDING_HASH__)";/, HASH_LINE);
        return stripWhitespaceOutsideStrings(normalized);
    }

    function stripWhitespaceOutsideStrings(source) {
        let output = "";
        let quote = "";
        let escaped = false;

        for (let i = 0; i < source.length; i++) {
            const char = source[i];

            if (quote) {
                output += char;
                if (escaped) {
                    escaped = false;
                } else if (char === "\\") {
                    escaped = true;
                } else if (char === quote) {
                    quote = "";
                }
                continue;
            }

            if (char === '"' || char === "'" || char === "`") {
                quote = char;
                output += char;
                continue;
            }

            if (/\s/.test(char)) {
                continue;
            }

            output += char;
        }

        return output;
    }

    async function sha256(text) {
        if (!window.crypto || !window.crypto.subtle || !window.TextEncoder) {
            return null;
        }
        const bytes = new TextEncoder().encode(text);
        const buffer = await window.crypto.subtle.digest("SHA-256", bytes);
        return "sha256:" + Array.from(new Uint8Array(buffer))
            .map((byte) => byte.toString(16).padStart(2, "0"))
            .join("");
    }

    function scriptUrl() {
        const script = loadedScript || document.querySelector('script[src$="utils.js"], script[src$="util.js"]');
        return script ? script.src : new URL("utils.js", window.location.href).href;
    }

    function check(category, name, points, passed, details = "", data = {}) {
        return {
            category,
            name,
            points,
            earned: passed === true ? points : 0,
            status: passed === null ? "SKIP" : passed ? "PASS" : "FAIL",
            passed,
            details,
            ...data,
        };
    }

    function summarize(checks) {
        const counted = checks.filter((item) => item.passed !== null && item.points > 0);
        const earned = counted.reduce((total, item) => total + item.earned, 0);
        const possible = counted.reduce((total, item) => total + item.points, 0);
        const passed = checks.filter((item) => item.passed === true).length;
        const failed = checks.filter((item) => item.passed === false).length;
        const skipped = checks.filter((item) => item.passed === null).length;
        return {
            earned: Number(earned.toFixed(2)),
            possible: Number(possible.toFixed(2)),
            percent: possible ? Number(((earned / possible) * 100).toFixed(1)) : 0,
            passed,
            failed,
            skipped,
            total: checks.length,
        };
    }

    function rectOf(selectorOrElement) {
        const element = typeof selectorOrElement === "string"
            ? document.querySelector(selectorOrElement)
            : selectorOrElement;
        return element ? element.getBoundingClientRect() : null;
    }

    function stylesOf(element) {
        return element ? window.getComputedStyle(element) : null;
    }

    function isVisible(element) {
        if (!element) {
            return false;
        }
        const rect = element.getBoundingClientRect();
        const styles = stylesOf(element);
        return rect.width > 0
            && rect.height > 0
            && styles.display !== "none"
            && styles.visibility !== "hidden"
            && Number(styles.opacity || 1) > 0;
    }

    function nearly(value, target, tolerance = 4) {
        return Math.abs(value - target) <= tolerance;
    }

    function sleep(ms = 150) {
        return new Promise((resolve) => window.setTimeout(resolve, ms));
    }

    function viewportHeight() {
        return window.innerHeight || document.documentElement.clientHeight;
    }

    function viewportWidth() {
        return window.innerWidth || document.documentElement.clientWidth;
    }

    function pageHasWindowScrollbar() {
        const html = document.documentElement;
        const body = document.body;
        return Math.max(html.scrollHeight, body.scrollHeight) > viewportHeight() + 3;
    }

    function scrollableCandidate(candidates) {
        return candidates.find((element) => {
            if (!element) {
                return false;
            }
            const styles = stylesOf(element);
            const overflow = `${styles.overflowY} ${styles.overflow}`;
            return element.scrollHeight > element.clientHeight + 20 && !/\b(visible|clip)\b/.test(overflow);
        }) || null;
    }

    function challengeName() {
        const body = document.body;
        if (body.classList.contains("challenge1")) {
            return "challenge1";
        }
        if (body.classList.contains("challenge2")) {
            return "challenge2";
        }
        if (body.classList.contains("challenge3")) {
            return "challenge3";
        }
        return "unknown";
    }

    async function tamperEvidence() {
        const checks = [];
        const url = scriptUrl();
        checks.push(check(
            "integrity",
            "helper script is loaded from utils.js",
            0,
            /\/utils\.js(?:[?#].*)?$/.test(url),
            url
        ));
        checks.push(check(
            "integrity",
            "expected utils.js hash is configured",
            0,
            /^sha256:[a-f0-9]{64}$/.test(EXPECTED_UTILS_HASH),
            EXPECTED_UTILS_HASH
        ));

        try {
            const response = await window.fetch(url, { cache: "no-store" });
            const source = await response.text();
            const actualHash = await sha256(normalizeSourceForHash(source));
            checks.push(check(
                "integrity",
                "fetched utils.js hash matches instructor baseline",
                0,
                actualHash === null ? null : actualHash === EXPECTED_UTILS_HASH,
                actualHash === null
                    ? "Web Crypto hashing unavailable in this browser"
                    : `expected ${EXPECTED_UTILS_HASH}, got ${actualHash}`
            ));
        } catch (error) {
            checks.push(check(
                "integrity",
                "fetched utils.js hash matches instructor baseline",
                0,
                null,
                `could not fetch helper script from this context: ${error.message}`
            ));
        }

        return checks;
    }

    function challenge1Checks() {
        const checks = [];
        const header = document.querySelector("header");
        const footer = document.querySelector("footer");
        const main = document.querySelector("main");
        const content = document.querySelector(".content");
        const scrollTarget = scrollableCandidate([content, main]);
        const bodyRect = rectOf(document.body);
        const headerRect = rectOf(header);
        const footerRect = rectOf(footer);
        const mainRect = rectOf(main);

        checks.push(check(
            "layout",
            "page fills the viewport without needing the browser window scrollbar",
            1,
            Boolean(bodyRect && bodyRect.height >= viewportHeight() - 4 && !pageHasWindowScrollbar()),
            `body height ${bodyRect ? Math.round(bodyRect.height) : "missing"}, viewport ${viewportHeight()}`
        ));

        checks.push(check(
            "layout",
            "content area scrolls independently",
            1,
            Boolean(scrollTarget),
            scrollTarget
                ? `scroll element ${scrollTarget.tagName.toLowerCase()}${scrollTarget.className ? "." + String(scrollTarget.className).trim().replace(/\s+/g, ".") : ""}`
                : "no independently scrollable content/main area found"
        ));

        checks.push(check(
            "layout",
            "header and footer remain visible at the top and bottom of the viewport",
            1,
            Boolean(
                headerRect
                && footerRect
                && headerRect.top >= -2
                && headerRect.bottom <= viewportHeight()
                && footerRect.bottom <= viewportHeight() + 2
                && footerRect.top >= 0
            ),
            `header ${headerRect ? Math.round(headerRect.top) + "-" + Math.round(headerRect.bottom) : "missing"}, footer ${footerRect ? Math.round(footerRect.top) + "-" + Math.round(footerRect.bottom) : "missing"}`
        ));

        const visibleBorders = [header, main, footer].every((element) => {
            const styles = stylesOf(element);
            return Boolean(styles && isVisible(element) && (styles.outlineStyle !== "none" || styles.boxShadow !== "none" || styles.borderStyle !== "none"));
        });
        checks.push(check(
            "layout",
            "header, main, and footer borders/outlines remain visible",
            1,
            visibleBorders && Boolean(mainRect && mainRect.height > 40),
            "checks outline, box-shadow, or border visibility on each required section"
        ));

        return checks;
    }

    async function challenge2Checks() {
        const checks = [];
        const header = document.querySelector("header");
        const container = document.querySelector(".container");
        const left = document.querySelector("#left-sidebar");
        const right = document.querySelector("#right-sidebar");
        const content = document.querySelector("main.content, .container .content");
        const leftButton = left ? left.querySelector("button") : null;
        const rightButton = right ? right.querySelector("button") : null;
        const headerRect = rectOf(header);
        const containerRect = rectOf(container);
        const leftRect = rectOf(left);
        const rightRect = rectOf(right);
        const contentRect = rectOf(content);

        checks.push(check(
            "layout",
            "header sits above the sidebar/content container",
            1,
            Boolean(headerRect && containerRect && headerRect.bottom <= containerRect.top + 4),
            `header bottom ${headerRect ? Math.round(headerRect.bottom) : "missing"}, container top ${containerRect ? Math.round(containerRect.top) : "missing"}`
        ));

        const containerFillsRest = Boolean(containerRect && containerRect.height >= viewportHeight() * 0.45 && containerRect.bottom <= viewportHeight() + 4);
        checks.push(check(
            "layout",
            "content container uses the remaining viewport height",
            1,
            containerFillsRest,
            `container height ${containerRect ? Math.round(containerRect.height) : "missing"}, viewport ${viewportHeight()}`
        ));

        const leftRatio = containerRect && leftRect ? leftRect.width / containerRect.width : 0;
        const rightRatio = containerRect && rightRect ? rightRect.width / containerRect.width : 0;
        checks.push(check(
            "layout",
            "expanded sidebars dock left/right at about 15% width each",
            1,
            Boolean(
                containerRect
                && leftRect
                && rightRect
                && leftRect.left <= containerRect.left + 4
                && rightRect.right >= containerRect.right - 4
                && leftRatio >= 0.10
                && leftRatio <= 0.22
                && rightRatio >= 0.10
                && rightRatio <= 0.22
            ),
            `left ${(leftRatio * 100).toFixed(1)}%, right ${(rightRatio * 100).toFixed(1)}%`
        ));

        checks.push(check(
            "layout",
            "main content uses the remaining horizontal space between sidebars",
            1,
            Boolean(
                leftRect
                && rightRect
                && contentRect
                && contentRect.left >= leftRect.right - 4
                && contentRect.right <= rightRect.left + 4
                && contentRect.width > Math.max(leftRect.width, rightRect.width)
            ),
            `content width ${contentRect ? Math.round(contentRect.width) : "missing"}`
        ));

        const leftToggle = await toggleCheck(leftButton, left, content, "left sidebar button toggles the left panel and keeps its button visible");
        const rightToggle = await toggleCheck(rightButton, right, content, "right sidebar button toggles the right panel and keeps its button visible");
        checks.push(leftToggle);
        checks.push(rightToggle);

        return checks;
    }

    async function toggleCheck(button, sidebar, content, name) {
        if (!button || !sidebar || !content) {
            return check("interaction", name, 1, false, "missing sidebar, button, or content element");
        }
        const beforeSidebar = sidebar.getBoundingClientRect().width;
        const beforeContent = content.getBoundingClientRect().width;
        button.click();
        await sleep();
        const afterSidebar = sidebar.getBoundingClientRect().width;
        const afterContent = content.getBoundingClientRect().width;
        const buttonStillVisible = isVisible(button);
        const changedSidebar = Math.abs(afterSidebar - beforeSidebar) >= 8;
        const changedContent = Math.abs(afterContent - beforeContent) >= 8;
        button.click();
        await sleep();
        return check(
            "interaction",
            name,
            1,
            changedSidebar && changedContent && buttonStillVisible,
            `sidebar width ${Math.round(beforeSidebar)} -> ${Math.round(afterSidebar)}, content width ${Math.round(beforeContent)} -> ${Math.round(afterContent)}, button visible ${buttonStillVisible}`
        );
    }

    function carouselButtons() {
        const buttons = Array.from(document.querySelectorAll("button"));
        return {
            previous: buttons.find((button) => /previous/i.test(button.textContent)),
            next: buttons.find((button) => /next/i.test(button.textContent)),
        };
    }

    function visiblePanelIndices() {
        const carousel = document.querySelector(".carousel");
        const carouselRect = rectOf(carousel);
        const panels = Array.from(document.querySelectorAll(".panel"));
        if (!carousel || !carouselRect || panels.length === 0) {
            return [];
        }
        return panels
            .map((panel, index) => {
                if (!isVisible(panel)) {
                    return { index, area: 0 };
                }
                const rect = panel.getBoundingClientRect();
                const width = Math.max(0, Math.min(rect.right, carouselRect.right) - Math.max(rect.left, carouselRect.left));
                const height = Math.max(0, Math.min(rect.bottom, carouselRect.bottom) - Math.max(rect.top, carouselRect.top));
                return { index, area: width * height };
            })
            .filter((item) => item.area > Math.max(100, carouselRect.width * carouselRect.height * 0.35))
            .map((item) => item.index);
    }

    function activePanelIndex() {
        const visible = visiblePanelIndices();
        return visible.length === 1 ? visible[0] : -1;
    }

    async function challenge3Checks() {
        const checks = [];
        const carousel = document.querySelector(".carousel");
        const container = document.querySelector(".carousel-container");
        const panels = Array.from(document.querySelectorAll(".panel"));
        const { previous, next } = carouselButtons();
        const carouselRect = rectOf(carousel);
        const controlsRect = previous && next
            ? {
                left: Math.min(previous.getBoundingClientRect().left, next.getBoundingClientRect().left),
                right: Math.max(previous.getBoundingClientRect().right, next.getBoundingClientRect().right),
            }
            : null;

        checks.push(check(
            "layout",
            "carousel spans the available page width",
            1,
            Boolean(carouselRect && carouselRect.width >= viewportWidth() * 0.85),
            `carousel width ${carouselRect ? Math.round(carouselRect.width) : "missing"}, viewport ${viewportWidth()}`
        ));

        checks.push(check(
            "layout",
            "Previous and Next buttons are centered as a control group",
            1,
            Boolean(controlsRect && nearly((controlsRect.left + controlsRect.right) / 2, viewportWidth() / 2, 40)),
            controlsRect ? `control center ${Math.round((controlsRect.left + controlsRect.right) / 2)}, viewport center ${Math.round(viewportWidth() / 2)}` : "missing Previous/Next buttons"
        ));

        checks.push(check(
            "layout",
            "only one carousel panel is visible at a time",
            1,
            visiblePanelIndices().length === 1,
            `visible panel indices: ${visiblePanelIndices().join(", ") || "none"}`
        ));

        const start = activePanelIndex();
        if (!previous || !next || !carousel || !container || panels.length === 0 || start < 0) {
            checks.push(check("interaction", "Next button advances one panel", 1, false, "missing carousel controls or a single active panel"));
            checks.push(check("interaction", "Previous button moves back and loops", 1, false, "missing carousel controls or a single active panel"));
            checks.push(check("interaction", "Next button loops back after the last panel", 1, false, "missing carousel controls or a single active panel"));
            checks.push(check("extra", "mouse swipe changes the active panel", 1, null, "not tested because the base carousel controls are incomplete"));
            return checks;
        }

        next.click();
        await sleep(300);
        const afterNext = activePanelIndex();
        checks.push(check(
            "interaction",
            "Next button advances one panel",
            1,
            afterNext === (start + 1) % panels.length,
            `expected ${(start + 1) % panels.length}, got ${afterNext}`
        ));

        previous.click();
        await sleep(300);
        const afterPrevious = activePanelIndex();
        checks.push(check(
            "interaction",
            "Previous button moves back from the current panel",
            1,
            afterPrevious === start,
            `expected ${start}, got ${afterPrevious}`
        ));

        for (let i = 0; i < panels.length; i++) {
            next.click();
            await sleep(120);
        }
        const afterLoop = activePanelIndex();
        checks.push(check(
            "interaction",
            "Next button loops back after the last panel",
            1,
            afterLoop === start,
            `expected ${start}, got ${afterLoop}`
        ));

        const beforeSwipe = activePanelIndex();
        await simulateSwipe(carousel);
        await sleep(300);
        const afterSwipe = activePanelIndex();
        checks.push(check(
            "extra",
            "mouse swipe changes the active panel",
            1,
            afterSwipe >= 0 && afterSwipe !== beforeSwipe,
            `before ${beforeSwipe}, after ${afterSwipe}`
        ));

        return checks;
    }

    async function simulateSwipe(element) {
        const rect = element.getBoundingClientRect();
        const y = rect.top + rect.height / 2;
        const startX = rect.left + rect.width * 0.75;
        const endX = rect.left + rect.width * 0.25;
        const options = { bubbles: true, cancelable: true, clientY: y };

        if (window.PointerEvent) {
            element.dispatchEvent(new PointerEvent("pointerdown", { ...options, pointerId: 1, clientX: startX }));
            element.dispatchEvent(new PointerEvent("pointermove", { ...options, pointerId: 1, clientX: endX }));
            element.dispatchEvent(new PointerEvent("pointerup", { ...options, pointerId: 1, clientX: endX }));
        }

        element.dispatchEvent(new MouseEvent("mousedown", { ...options, clientX: startX }));
        element.dispatchEvent(new MouseEvent("mousemove", { ...options, clientX: endX }));
        element.dispatchEvent(new MouseEvent("mouseup", { ...options, clientX: endX }));
        await sleep(50);
    }

    async function run(challenge = challengeName()) {
        setupPage();
        const integrityChecks = await tamperEvidence();
        let challengeChecks = [];

        if (challenge === "challenge1") {
            challengeChecks = challenge1Checks();
        } else if (challenge === "challenge2") {
            challengeChecks = await challenge2Checks();
        } else if (challenge === "challenge3") {
            challengeChecks = await challenge3Checks();
        } else {
            integrityChecks.push(check("consistency", "recognized challenge page", 0, false, document.body.className));
        }

        const challengeSummary = summarize(challengeChecks);
        const integritySummary = summarize(integrityChecks);

        return {
            assignment: "m03",
            challenge,
            version: VERSION,
            timestamp: new Date().toISOString(),
            summary: challengeSummary,
            challengeSummary,
            integritySummary,
            checks: challengeChecks,
            challengeChecks,
            integrityChecks,
            allChecks: integrityChecks.concat(challengeChecks),
            groups: {
                integrity: {
                    label: "Integrity / Consistency",
                    scored: false,
                    summary: integritySummary,
                    checks: integrityChecks,
                },
                challenge: {
                    label: "Challenge Solution",
                    scored: true,
                    summary: challengeSummary,
                    checks: challengeChecks,
                },
            },
        };
    }

    async function print(challenge) {
        const result = await run(challenge);
        const rowFor = (item) => ({
            status: item.status,
            category: item.category,
            name: item.name,
            points: `${item.earned}/${item.points}`,
            details: item.details,
        });

        console.group("M03 integrity / consistency checks (not scored)");
        console.table(result.integrityChecks.map(rowFor));
        console.log("M03 integrity summary:", result.integritySummary);
        console.groupEnd();

        console.group("M03 challenge solution checks (scored)");
        console.table(result.challengeChecks.map(rowFor));
        console.log("M03 challenge score:", result.challengeSummary);
        console.groupEnd();

        return result;
    }

    setupPage();
    window.M03Grader = Object.freeze({
        version: VERSION,
        expectedUtilsHash: EXPECTED_UTILS_HASH,
        run,
        print,
        tamperEvidence,
    });
    window.M03_GRADER = window.M03Grader;
})();