
CREATE TABLE M4_Todos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    task VARCHAR(128) NOT NULL,
    due DATE NOT NULL DEFAULT (CURRENT_DATE),
    assigned VARCHAR(60) NOT NULL DEFAULT 'self',
    is_complete TINYINT(1) NOT NULL DEFAULT 0,
    completed TIMESTAMP DEFAULT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE (task, due)
);