CREATE TABLE UserFlights (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    user_id INT NOT NULL,
    flight_id INT UNSIGNED NOT NULL,

    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE (user_id, flight_id),

    FOREIGN KEY (user_id)
        REFERENCES Users(id)
        ON DELETE CASCADE,

    FOREIGN KEY (flight_id)
        REFERENCES Flights(id)
        ON DELETE CASCADE
);